// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvpb.proto

package kv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxnRequestType int32

const (
	TxnRequestType_Invalid  TxnRequestType = 0
	TxnRequestType_Begin    TxnRequestType = 1
	TxnRequestType_Commit   TxnRequestType = 2
	TxnRequestType_Rollback TxnRequestType = 3
	TxnRequestType_Get      TxnRequestType = 4
	TxnRequestType_Put      TxnRequestType = 5
	TxnRequestType_Delete   TxnRequestType = 6
	TxnRequestType_Scan     TxnRequestType = 7
)

var TxnRequestType_name = map[int32]string{
	0: "Invalid",
	1: "Begin",
	2: "Commit",
	3: "Rollback",
	4: "Get",
	5: "Put",
	6: "Delete",
	7: "Scan",
}

var TxnRequestType_value = map[string]int32{
	"Invalid":  0,
	"Begin":    1,
	"Commit":   2,
	"Rollback": 3,
	"Get":      4,
	"Put":      5,
	"Delete":   6,
	"Scan":     7,
}

func (x TxnRequestType) String() string {
	return proto.EnumName(TxnRequestType_name, int32(x))
}

func (TxnRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{0}
}

type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type KvPair struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvPair) Reset()         { *m = KvPair{} }
func (m *KvPair) String() string { return proto.CompactTextString(m) }
func (*KvPair) ProtoMessage()    {}
func (*KvPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{1}
}

func (m *KvPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvPair.Unmarshal(m, b)
}
func (m *KvPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvPair.Marshal(b, m, deterministic)
}
func (m *KvPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvPair.Merge(m, src)
}
func (m *KvPair) XXX_Size() int {
	return xxx_messageInfo_KvPair.Size(m)
}
func (m *KvPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KvPair.DiscardUnknown(m)
}

var xxx_messageInfo_KvPair proto.InternalMessageInfo

func (m *KvPair) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KvPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{4}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{5}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ScanRequest struct {
	StartKey             []byte   `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               []byte   `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Desc                 bool     `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{8}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *ScanRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *ScanRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ScanRequest) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

type ScanResponse struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Pairs                []*KvPair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{9}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ScanResponse) GetPairs() []*KvPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type TxnSetRequest struct {
	AutoCommit           bool     `protobuf:"varint,1,opt,name=auto_commit,json=autoCommit,proto3" json:"auto_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnSetRequest) Reset()         { *m = TxnSetRequest{} }
func (m *TxnSetRequest) String() string { return proto.CompactTextString(m) }
func (*TxnSetRequest) ProtoMessage()    {}
func (*TxnSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{10}
}

func (m *TxnSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnSetRequest.Unmarshal(m, b)
}
func (m *TxnSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnSetRequest.Marshal(b, m, deterministic)
}
func (m *TxnSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnSetRequest.Merge(m, src)
}
func (m *TxnSetRequest) XXX_Size() int {
	return xxx_messageInfo_TxnSetRequest.Size(m)
}
func (m *TxnSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnSetRequest proto.InternalMessageInfo

func (m *TxnSetRequest) GetAutoCommit() bool {
	if m != nil {
		return m.AutoCommit
	}
	return false
}

type TxnSetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnSetResponse) Reset()         { *m = TxnSetResponse{} }
func (m *TxnSetResponse) String() string { return proto.CompactTextString(m) }
func (*TxnSetResponse) ProtoMessage()    {}
func (*TxnSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{11}
}

func (m *TxnSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnSetResponse.Unmarshal(m, b)
}
func (m *TxnSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnSetResponse.Marshal(b, m, deterministic)
}
func (m *TxnSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnSetResponse.Merge(m, src)
}
func (m *TxnSetResponse) XXX_Size() int {
	return xxx_messageInfo_TxnSetResponse.Size(m)
}
func (m *TxnSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnSetResponse proto.InternalMessageInfo

type TxnBeginRequest struct {
	// Start a transaction with a special timestamp explicitly.
	StartTs              uint64   `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnBeginRequest) Reset()         { *m = TxnBeginRequest{} }
func (m *TxnBeginRequest) String() string { return proto.CompactTextString(m) }
func (*TxnBeginRequest) ProtoMessage()    {}
func (*TxnBeginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{12}
}

func (m *TxnBeginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnBeginRequest.Unmarshal(m, b)
}
func (m *TxnBeginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnBeginRequest.Marshal(b, m, deterministic)
}
func (m *TxnBeginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnBeginRequest.Merge(m, src)
}
func (m *TxnBeginRequest) XXX_Size() int {
	return xxx_messageInfo_TxnBeginRequest.Size(m)
}
func (m *TxnBeginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnBeginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnBeginRequest proto.InternalMessageInfo

func (m *TxnBeginRequest) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

type TxnBeginResponse struct {
	StartTs              uint64   `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnBeginResponse) Reset()         { *m = TxnBeginResponse{} }
func (m *TxnBeginResponse) String() string { return proto.CompactTextString(m) }
func (*TxnBeginResponse) ProtoMessage()    {}
func (*TxnBeginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{13}
}

func (m *TxnBeginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnBeginResponse.Unmarshal(m, b)
}
func (m *TxnBeginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnBeginResponse.Marshal(b, m, deterministic)
}
func (m *TxnBeginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnBeginResponse.Merge(m, src)
}
func (m *TxnBeginResponse) XXX_Size() int {
	return xxx_messageInfo_TxnBeginResponse.Size(m)
}
func (m *TxnBeginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnBeginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnBeginResponse proto.InternalMessageInfo

func (m *TxnBeginResponse) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

type TxnCommitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnCommitRequest) Reset()         { *m = TxnCommitRequest{} }
func (m *TxnCommitRequest) String() string { return proto.CompactTextString(m) }
func (*TxnCommitRequest) ProtoMessage()    {}
func (*TxnCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{14}
}

func (m *TxnCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnCommitRequest.Unmarshal(m, b)
}
func (m *TxnCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnCommitRequest.Marshal(b, m, deterministic)
}
func (m *TxnCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnCommitRequest.Merge(m, src)
}
func (m *TxnCommitRequest) XXX_Size() int {
	return xxx_messageInfo_TxnCommitRequest.Size(m)
}
func (m *TxnCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnCommitRequest proto.InternalMessageInfo

type TxnCommitResponse struct {
	CommitTs             uint64   `protobuf:"varint,1,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnCommitResponse) Reset()         { *m = TxnCommitResponse{} }
func (m *TxnCommitResponse) String() string { return proto.CompactTextString(m) }
func (*TxnCommitResponse) ProtoMessage()    {}
func (*TxnCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{15}
}

func (m *TxnCommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnCommitResponse.Unmarshal(m, b)
}
func (m *TxnCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnCommitResponse.Marshal(b, m, deterministic)
}
func (m *TxnCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnCommitResponse.Merge(m, src)
}
func (m *TxnCommitResponse) XXX_Size() int {
	return xxx_messageInfo_TxnCommitResponse.Size(m)
}
func (m *TxnCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnCommitResponse proto.InternalMessageInfo

func (m *TxnCommitResponse) GetCommitTs() uint64 {
	if m != nil {
		return m.CommitTs
	}
	return 0
}

type TxnRollbackRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnRollbackRequest) Reset()         { *m = TxnRollbackRequest{} }
func (m *TxnRollbackRequest) String() string { return proto.CompactTextString(m) }
func (*TxnRollbackRequest) ProtoMessage()    {}
func (*TxnRollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{16}
}

func (m *TxnRollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnRollbackRequest.Unmarshal(m, b)
}
func (m *TxnRollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnRollbackRequest.Marshal(b, m, deterministic)
}
func (m *TxnRollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnRollbackRequest.Merge(m, src)
}
func (m *TxnRollbackRequest) XXX_Size() int {
	return xxx_messageInfo_TxnRollbackRequest.Size(m)
}
func (m *TxnRollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnRollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnRollbackRequest proto.InternalMessageInfo

type TxnRollbackResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnRollbackResponse) Reset()         { *m = TxnRollbackResponse{} }
func (m *TxnRollbackResponse) String() string { return proto.CompactTextString(m) }
func (*TxnRollbackResponse) ProtoMessage()    {}
func (*TxnRollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{17}
}

func (m *TxnRollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnRollbackResponse.Unmarshal(m, b)
}
func (m *TxnRollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnRollbackResponse.Marshal(b, m, deterministic)
}
func (m *TxnRollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnRollbackResponse.Merge(m, src)
}
func (m *TxnRollbackResponse) XXX_Size() int {
	return xxx_messageInfo_TxnRollbackResponse.Size(m)
}
func (m *TxnRollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnRollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnRollbackResponse proto.InternalMessageInfo

type TxnGetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnGetRequest) Reset()         { *m = TxnGetRequest{} }
func (m *TxnGetRequest) String() string { return proto.CompactTextString(m) }
func (*TxnGetRequest) ProtoMessage()    {}
func (*TxnGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{18}
}

func (m *TxnGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnGetRequest.Unmarshal(m, b)
}
func (m *TxnGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnGetRequest.Marshal(b, m, deterministic)
}
func (m *TxnGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnGetRequest.Merge(m, src)
}
func (m *TxnGetRequest) XXX_Size() int {
	return xxx_messageInfo_TxnGetRequest.Size(m)
}
func (m *TxnGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnGetRequest proto.InternalMessageInfo

func (m *TxnGetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type TxnGetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnGetResponse) Reset()         { *m = TxnGetResponse{} }
func (m *TxnGetResponse) String() string { return proto.CompactTextString(m) }
func (*TxnGetResponse) ProtoMessage()    {}
func (*TxnGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{19}
}

func (m *TxnGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnGetResponse.Unmarshal(m, b)
}
func (m *TxnGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnGetResponse.Marshal(b, m, deterministic)
}
func (m *TxnGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnGetResponse.Merge(m, src)
}
func (m *TxnGetResponse) XXX_Size() int {
	return xxx_messageInfo_TxnGetResponse.Size(m)
}
func (m *TxnGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnGetResponse proto.InternalMessageInfo

func (m *TxnGetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TxnPutRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnPutRequest) Reset()         { *m = TxnPutRequest{} }
func (m *TxnPutRequest) String() string { return proto.CompactTextString(m) }
func (*TxnPutRequest) ProtoMessage()    {}
func (*TxnPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{20}
}

func (m *TxnPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnPutRequest.Unmarshal(m, b)
}
func (m *TxnPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnPutRequest.Marshal(b, m, deterministic)
}
func (m *TxnPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnPutRequest.Merge(m, src)
}
func (m *TxnPutRequest) XXX_Size() int {
	return xxx_messageInfo_TxnPutRequest.Size(m)
}
func (m *TxnPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnPutRequest proto.InternalMessageInfo

func (m *TxnPutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TxnPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TxnPutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnPutResponse) Reset()         { *m = TxnPutResponse{} }
func (m *TxnPutResponse) String() string { return proto.CompactTextString(m) }
func (*TxnPutResponse) ProtoMessage()    {}
func (*TxnPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{21}
}

func (m *TxnPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnPutResponse.Unmarshal(m, b)
}
func (m *TxnPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnPutResponse.Marshal(b, m, deterministic)
}
func (m *TxnPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnPutResponse.Merge(m, src)
}
func (m *TxnPutResponse) XXX_Size() int {
	return xxx_messageInfo_TxnPutResponse.Size(m)
}
func (m *TxnPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnPutResponse proto.InternalMessageInfo

type TxnDeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnDeleteRequest) Reset()         { *m = TxnDeleteRequest{} }
func (m *TxnDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TxnDeleteRequest) ProtoMessage()    {}
func (*TxnDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{22}
}

func (m *TxnDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnDeleteRequest.Unmarshal(m, b)
}
func (m *TxnDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnDeleteRequest.Marshal(b, m, deterministic)
}
func (m *TxnDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnDeleteRequest.Merge(m, src)
}
func (m *TxnDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TxnDeleteRequest.Size(m)
}
func (m *TxnDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnDeleteRequest proto.InternalMessageInfo

func (m *TxnDeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type TxnDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnDeleteResponse) Reset()         { *m = TxnDeleteResponse{} }
func (m *TxnDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*TxnDeleteResponse) ProtoMessage()    {}
func (*TxnDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{23}
}

func (m *TxnDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnDeleteResponse.Unmarshal(m, b)
}
func (m *TxnDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnDeleteResponse.Marshal(b, m, deterministic)
}
func (m *TxnDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnDeleteResponse.Merge(m, src)
}
func (m *TxnDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_TxnDeleteResponse.Size(m)
}
func (m *TxnDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnDeleteResponse proto.InternalMessageInfo

type TxnScanRequest struct {
	StartKey []byte `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey   []byte `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit    uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// When scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
	// When scanning backward, it scans [end_key, start_key) in descending order, where
	Desc                 bool     `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxnScanRequest) Reset()         { *m = TxnScanRequest{} }
func (m *TxnScanRequest) String() string { return proto.CompactTextString(m) }
func (*TxnScanRequest) ProtoMessage()    {}
func (*TxnScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{24}
}

func (m *TxnScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnScanRequest.Unmarshal(m, b)
}
func (m *TxnScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnScanRequest.Marshal(b, m, deterministic)
}
func (m *TxnScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnScanRequest.Merge(m, src)
}
func (m *TxnScanRequest) XXX_Size() int {
	return xxx_messageInfo_TxnScanRequest.Size(m)
}
func (m *TxnScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnScanRequest proto.InternalMessageInfo

func (m *TxnScanRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *TxnScanRequest) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *TxnScanRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *TxnScanRequest) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

type TxnScanResponse struct {
	Pairs                []*KvPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TxnScanResponse) Reset()         { *m = TxnScanResponse{} }
func (m *TxnScanResponse) String() string { return proto.CompactTextString(m) }
func (*TxnScanResponse) ProtoMessage()    {}
func (*TxnScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{25}
}

func (m *TxnScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnScanResponse.Unmarshal(m, b)
}
func (m *TxnScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnScanResponse.Marshal(b, m, deterministic)
}
func (m *TxnScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnScanResponse.Merge(m, src)
}
func (m *TxnScanResponse) XXX_Size() int {
	return xxx_messageInfo_TxnScanResponse.Size(m)
}
func (m *TxnScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnScanResponse proto.InternalMessageInfo

func (m *TxnScanResponse) GetPairs() []*KvPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type TxnRequest struct {
	ReqType              TxnRequestType      `protobuf:"varint,1,opt,name=req_type,json=reqType,proto3,enum=kv.TxnRequestType" json:"req_type,omitempty"`
	Set                  *TxnSetRequest      `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Begin                *TxnBeginRequest    `protobuf:"bytes,3,opt,name=begin,proto3" json:"begin,omitempty"`
	Commit               *TxnCommitRequest   `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	Rollback             *TxnRollbackRequest `protobuf:"bytes,5,opt,name=rollback,proto3" json:"rollback,omitempty"`
	Get                  *TxnGetRequest      `protobuf:"bytes,6,opt,name=get,proto3" json:"get,omitempty"`
	Put                  *TxnPutRequest      `protobuf:"bytes,7,opt,name=put,proto3" json:"put,omitempty"`
	Delete               *TxnDeleteRequest   `protobuf:"bytes,8,opt,name=delete,proto3" json:"delete,omitempty"`
	Scan                 *TxnScanRequest     `protobuf:"bytes,9,opt,name=scan,proto3" json:"scan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxnRequest) Reset()         { *m = TxnRequest{} }
func (m *TxnRequest) String() string { return proto.CompactTextString(m) }
func (*TxnRequest) ProtoMessage()    {}
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{26}
}

func (m *TxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnRequest.Unmarshal(m, b)
}
func (m *TxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnRequest.Marshal(b, m, deterministic)
}
func (m *TxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnRequest.Merge(m, src)
}
func (m *TxnRequest) XXX_Size() int {
	return xxx_messageInfo_TxnRequest.Size(m)
}
func (m *TxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxnRequest proto.InternalMessageInfo

func (m *TxnRequest) GetReqType() TxnRequestType {
	if m != nil {
		return m.ReqType
	}
	return TxnRequestType_Invalid
}

func (m *TxnRequest) GetSet() *TxnSetRequest {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *TxnRequest) GetBegin() *TxnBeginRequest {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *TxnRequest) GetCommit() *TxnCommitRequest {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *TxnRequest) GetRollback() *TxnRollbackRequest {
	if m != nil {
		return m.Rollback
	}
	return nil
}

func (m *TxnRequest) GetGet() *TxnGetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *TxnRequest) GetPut() *TxnPutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *TxnRequest) GetDelete() *TxnDeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *TxnRequest) GetScan() *TxnScanRequest {
	if m != nil {
		return m.Scan
	}
	return nil
}

type TxnResponse struct {
	Error                *Error               `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ReqType              TxnRequestType       `protobuf:"varint,2,opt,name=req_type,json=reqType,proto3,enum=kv.TxnRequestType" json:"req_type,omitempty"`
	Set                  *TxnSetResponse      `protobuf:"bytes,3,opt,name=set,proto3" json:"set,omitempty"`
	Begin                *TxnBeginResponse    `protobuf:"bytes,4,opt,name=begin,proto3" json:"begin,omitempty"`
	Commit               *TxnCommitResponse   `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	Rollback             *TxnRollbackResponse `protobuf:"bytes,6,opt,name=rollback,proto3" json:"rollback,omitempty"`
	Get                  *TxnGetResponse      `protobuf:"bytes,7,opt,name=get,proto3" json:"get,omitempty"`
	Put                  *TxnPutResponse      `protobuf:"bytes,8,opt,name=put,proto3" json:"put,omitempty"`
	Delete               *TxnDeleteResponse   `protobuf:"bytes,9,opt,name=delete,proto3" json:"delete,omitempty"`
	Scan                 *TxnScanResponse     `protobuf:"bytes,10,opt,name=scan,proto3" json:"scan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TxnResponse) Reset()         { *m = TxnResponse{} }
func (m *TxnResponse) String() string { return proto.CompactTextString(m) }
func (*TxnResponse) ProtoMessage()    {}
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d46ba518369a41, []int{27}
}

func (m *TxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxnResponse.Unmarshal(m, b)
}
func (m *TxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxnResponse.Marshal(b, m, deterministic)
}
func (m *TxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnResponse.Merge(m, src)
}
func (m *TxnResponse) XXX_Size() int {
	return xxx_messageInfo_TxnResponse.Size(m)
}
func (m *TxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxnResponse proto.InternalMessageInfo

func (m *TxnResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TxnResponse) GetReqType() TxnRequestType {
	if m != nil {
		return m.ReqType
	}
	return TxnRequestType_Invalid
}

func (m *TxnResponse) GetSet() *TxnSetResponse {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *TxnResponse) GetBegin() *TxnBeginResponse {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *TxnResponse) GetCommit() *TxnCommitResponse {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *TxnResponse) GetRollback() *TxnRollbackResponse {
	if m != nil {
		return m.Rollback
	}
	return nil
}

func (m *TxnResponse) GetGet() *TxnGetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *TxnResponse) GetPut() *TxnPutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *TxnResponse) GetDelete() *TxnDeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *TxnResponse) GetScan() *TxnScanResponse {
	if m != nil {
		return m.Scan
	}
	return nil
}

func init() {
	proto.RegisterEnum("kv.TxnRequestType", TxnRequestType_name, TxnRequestType_value)
	proto.RegisterType((*Error)(nil), "kv.Error")
	proto.RegisterType((*KvPair)(nil), "kv.KvPair")
	proto.RegisterType((*GetRequest)(nil), "kv.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "kv.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "kv.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "kv.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "kv.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "kv.DeleteResponse")
	proto.RegisterType((*ScanRequest)(nil), "kv.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "kv.ScanResponse")
	proto.RegisterType((*TxnSetRequest)(nil), "kv.TxnSetRequest")
	proto.RegisterType((*TxnSetResponse)(nil), "kv.TxnSetResponse")
	proto.RegisterType((*TxnBeginRequest)(nil), "kv.TxnBeginRequest")
	proto.RegisterType((*TxnBeginResponse)(nil), "kv.TxnBeginResponse")
	proto.RegisterType((*TxnCommitRequest)(nil), "kv.TxnCommitRequest")
	proto.RegisterType((*TxnCommitResponse)(nil), "kv.TxnCommitResponse")
	proto.RegisterType((*TxnRollbackRequest)(nil), "kv.TxnRollbackRequest")
	proto.RegisterType((*TxnRollbackResponse)(nil), "kv.TxnRollbackResponse")
	proto.RegisterType((*TxnGetRequest)(nil), "kv.TxnGetRequest")
	proto.RegisterType((*TxnGetResponse)(nil), "kv.TxnGetResponse")
	proto.RegisterType((*TxnPutRequest)(nil), "kv.TxnPutRequest")
	proto.RegisterType((*TxnPutResponse)(nil), "kv.TxnPutResponse")
	proto.RegisterType((*TxnDeleteRequest)(nil), "kv.TxnDeleteRequest")
	proto.RegisterType((*TxnDeleteResponse)(nil), "kv.TxnDeleteResponse")
	proto.RegisterType((*TxnScanRequest)(nil), "kv.TxnScanRequest")
	proto.RegisterType((*TxnScanResponse)(nil), "kv.TxnScanResponse")
	proto.RegisterType((*TxnRequest)(nil), "kv.TxnRequest")
	proto.RegisterType((*TxnResponse)(nil), "kv.TxnResponse")
}

func init() { proto.RegisterFile("kvpb.proto", fileDescriptor_79d46ba518369a41) }

var fileDescriptor_79d46ba518369a41 = []byte{
	// 872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0x8d, 0x2c, 0xcb, 0x92, 0xaf, 0xf2, 0xa1, 0x32, 0xe9, 0xaa, 0xae, 0xc0, 0xea, 0x72, 0x41,
	0xe7, 0x15, 0x89, 0x91, 0x39, 0x05, 0xf6, 0xde, 0x75, 0x08, 0x06, 0x3f, 0x2c, 0x63, 0xfd, 0xb6,
	0x87, 0x40, 0xb1, 0x09, 0x43, 0xb3, 0x23, 0x29, 0x12, 0xa5, 0x25, 0x3f, 0x62, 0xbf, 0x67, 0x7f,
	0x6f, 0xe0, 0x25, 0xf5, 0xc1, 0x15, 0x6e, 0x8c, 0x3d, 0xec, 0x8d, 0x22, 0xcf, 0xbd, 0xf7, 0xdc,
	0x7b, 0x0e, 0x09, 0x01, 0xac, 0xab, 0xec, 0x76, 0x92, 0xe5, 0xa9, 0x48, 0x49, 0x6f, 0x5d, 0xd1,
	0x97, 0xe0, 0xfc, 0x9c, 0xe7, 0x69, 0x4e, 0x02, 0xb0, 0xef, 0x8a, 0x55, 0x68, 0x8d, 0xac, 0xf1,
	0x90, 0xc9, 0x25, 0xbd, 0x80, 0xc1, 0xac, 0xba, 0x8e, 0x62, 0x3c, 0x5b, 0xf3, 0x47, 0x3c, 0xdb,
	0x67, 0x72, 0x49, 0x4e, 0xc0, 0xa9, 0xa2, 0x4d, 0xc9, 0xc3, 0x1e, 0xee, 0xa9, 0x0f, 0xfa, 0x0d,
	0xc0, 0x15, 0x17, 0x8c, 0xdf, 0x97, 0xbc, 0x10, 0x9f, 0x47, 0xd1, 0x8f, 0xe0, 0xe3, 0x79, 0x91,
	0xa5, 0x49, 0xc1, 0xc9, 0x6b, 0x70, 0xb8, 0xac, 0x8d, 0x10, 0x7f, 0x3a, 0x9c, 0xac, 0xab, 0x09,
	0x92, 0x61, 0x6a, 0x7f, 0x4b, 0x95, 0xf7, 0x00, 0xd7, 0xe5, 0xf6, 0x2a, 0x5b, 0xa2, 0x26, 0xe0,
	0x63, 0xd4, 0x8e, 0xb5, 0xe9, 0x1b, 0x38, 0xf8, 0xc8, 0x37, 0x5c, 0xf0, 0xed, 0xed, 0xfc, 0x00,
	0x87, 0x35, 0x64, 0xd7, 0xac, 0x77, 0xe0, 0x7f, 0x5a, 0x44, 0x49, 0x9d, 0xf3, 0x15, 0x0c, 0x0b,
	0x11, 0xe5, 0xe2, 0xa6, 0xcd, 0xec, 0xe1, 0xc6, 0x8c, 0x3f, 0x92, 0x17, 0xe0, 0xf2, 0x64, 0x89,
	0x47, 0xaa, 0x93, 0x01, 0x4f, 0x96, 0x33, 0xd5, 0xe0, 0x26, 0xbe, 0x8b, 0x45, 0x68, 0x8f, 0xac,
	0xf1, 0x01, 0x53, 0x1f, 0x84, 0x40, 0x7f, 0xc9, 0x8b, 0x45, 0xd8, 0x1f, 0x59, 0x63, 0x8f, 0xe1,
	0x9a, 0xfe, 0x06, 0xfb, 0xaa, 0xdc, 0xae, 0x13, 0x1f, 0x81, 0x93, 0x45, 0x71, 0x5e, 0x84, 0xbd,
	0x91, 0x3d, 0xf6, 0xa7, 0x20, 0x01, 0xca, 0x04, 0x4c, 0x1d, 0xd0, 0x0b, 0x38, 0x98, 0x3f, 0x24,
	0x9f, 0x5a, 0x99, 0x5f, 0x83, 0x1f, 0x95, 0x22, 0xbd, 0x59, 0xa4, 0x77, 0x92, 0x93, 0x85, 0xe5,
	0x41, 0x6e, 0xfd, 0x84, 0x3b, 0x34, 0x80, 0xc3, 0x3a, 0x42, 0xd1, 0xa0, 0x67, 0x70, 0x34, 0x7f,
	0x48, 0x3e, 0xf0, 0x55, 0xdc, 0x4c, 0xe2, 0x25, 0xa8, 0xc6, 0x6f, 0x44, 0x81, 0x29, 0xfa, 0xcc,
	0xc5, 0xef, 0x79, 0x41, 0xcf, 0x21, 0x68, 0xd1, 0xba, 0x91, 0x2f, 0xc0, 0x09, 0xc2, 0x55, 0x6d,
	0x9d, 0x9d, 0x5e, 0xc0, 0xb3, 0xce, 0x9e, 0xce, 0xf1, 0x0a, 0x86, 0x8a, 0x73, 0x9b, 0xc4, 0x53,
	0x1b, 0xf3, 0x82, 0x9e, 0x00, 0x99, 0x3f, 0x24, 0x2c, 0xdd, 0x6c, 0x6e, 0xa3, 0xc5, 0xba, 0xce,
	0xf3, 0x1c, 0x8e, 0x8d, 0x5d, 0xdd, 0xcf, 0x1b, 0x9c, 0xc9, 0x17, 0xad, 0xff, 0x16, 0x87, 0xd0,
	0x75, 0x7f, 0x63, 0x53, 0xab, 0x6b, 0xd3, 0x1f, 0x31, 0xd5, 0x7f, 0xf0, 0xb7, 0x9a, 0x72, 0xc7,
	0xe2, 0xf4, 0x14, 0x07, 0xf1, 0x94, 0x89, 0x8f, 0x71, 0x34, 0xa6, 0x8f, 0x69, 0xa6, 0x24, 0xfb,
	0x1f, 0x9d, 0x7a, 0x89, 0x96, 0x30, 0xcc, 0xda, 0x78, 0xd1, 0xda, 0xe6, 0xc5, 0xbf, 0x6c, 0x00,
	0xa9, 0x87, 0xe6, 0x78, 0x0e, 0x5e, 0xce, 0xef, 0x6f, 0xc4, 0x63, 0xa6, 0x86, 0x7a, 0x38, 0x25,
	0x32, 0xa6, 0x45, 0xcc, 0x1f, 0x33, 0xce, 0xdc, 0x9c, 0xdf, 0xcb, 0x05, 0xf9, 0x16, 0xec, 0x82,
	0x0b, 0x64, 0xec, 0x4f, 0x9f, 0x69, 0x64, 0x6b, 0x6c, 0x26, 0x4f, 0xc9, 0xf7, 0xe0, 0xdc, 0x4a,
	0xe7, 0x61, 0x07, 0xfe, 0xf4, 0x58, 0xc3, 0xba, 0xde, 0x65, 0x0a, 0x41, 0xce, 0x60, 0xa0, 0xef,
	0x40, 0x1f, 0xb1, 0x27, 0x1a, 0x6b, 0x58, 0x91, 0x69, 0x0c, 0x99, 0x82, 0x97, 0x6b, 0x1f, 0x85,
	0x0e, 0xe2, 0xbf, 0xaa, 0xc9, 0x9a, 0xa6, 0x63, 0x0d, 0x4e, 0x32, 0x5e, 0x71, 0x11, 0x0e, 0x0c,
	0xc6, 0x57, 0x1d, 0xc6, 0x2b, 0x2e, 0x24, 0x28, 0x2b, 0x45, 0xe8, 0x1a, 0xa0, 0xd6, 0x50, 0x4c,
	0x9e, 0x4a, 0xae, 0x4b, 0x94, 0x3c, 0xf4, 0x0c, 0xae, 0x86, 0x5b, 0x98, 0xc6, 0x90, 0xb7, 0xd0,
	0x2f, 0x16, 0x51, 0x12, 0x0e, 0x11, 0x5b, 0x0f, 0xb5, 0x63, 0x0f, 0x86, 0xe7, 0xf4, 0x6f, 0x1b,
	0x7c, 0x9c, 0xf6, 0xae, 0xcf, 0x4d, 0x57, 0xb1, 0xde, 0xd3, 0x8a, 0x9d, 0x2a, 0xc5, 0x6c, 0x93,
	0x46, 0x7b, 0xa7, 0x94, 0x64, 0xef, 0x6a, 0xc9, 0x4c, 0x19, 0x8c, 0x07, 0xa4, 0xd6, 0xec, 0xbc,
	0xd1, 0x4c, 0x69, 0xf0, 0xfc, 0x5f, 0x9a, 0x69, 0x74, 0x2d, 0xda, 0x65, 0x47, 0x34, 0xa5, 0xc2,
	0x8b, 0xcf, 0x44, 0xd3, 0x21, 0xad, 0x6a, 0xa7, 0x4a, 0x35, 0xd7, 0x60, 0x7d, 0xd5, 0x65, 0x2d,
	0x65, 0x3b, 0x55, 0xb2, 0x79, 0x06, 0xaa, 0x73, 0x9d, 0x95, 0x6e, 0xe7, 0x8d, 0x6e, 0x43, 0x83,
	0xaf, 0x79, 0x7f, 0x1b, 0xe1, 0xbe, 0xd3, 0xc2, 0x81, 0x61, 0xde, 0xee, 0x2d, 0x53, 0xca, 0xbd,
	0xfb, 0x03, 0x2f, 0x7c, 0x67, 0xe8, 0xc4, 0x07, 0xf7, 0x97, 0xa4, 0x8a, 0x36, 0xf1, 0x32, 0xd8,
	0x23, 0x43, 0x70, 0x70, 0x7c, 0x81, 0x45, 0x00, 0x06, 0x6a, 0x38, 0x41, 0x8f, 0xec, 0x83, 0x57,
	0xf7, 0x1d, 0xd8, 0xc4, 0x05, 0xfb, 0x8a, 0x8b, 0xa0, 0x2f, 0x17, 0xd7, 0xa5, 0x08, 0x1c, 0x89,
	0x55, 0xc4, 0x82, 0x01, 0xf1, 0xa0, 0x2f, 0xeb, 0x06, 0xee, 0xf4, 0x77, 0x70, 0x58, 0xf4, 0xe7,
	0xac, 0x22, 0x63, 0x0c, 0x20, 0x87, 0x92, 0x56, 0xeb, 0xe2, 0xaf, 0x8f, 0x9a, 0x6f, 0xfd, 0x1a,
	0xed, 0x49, 0xe4, 0x75, 0xa9, 0x91, 0xad, 0x95, 0x15, 0xb2, 0xfb, 0xe4, 0xed, 0x4d, 0xd7, 0xe0,
	0xcc, 0x1f, 0x92, 0x59, 0x45, 0xde, 0x83, 0x3f, 0xcf, 0xa3, 0xa4, 0x88, 0x16, 0x22, 0x4e, 0x13,
	0x15, 0xda, 0xb6, 0xa8, 0x42, 0x3b, 0x5e, 0xa5, 0x7b, 0x63, 0xeb, 0xc2, 0x22, 0x67, 0xe0, 0xb2,
	0x32, 0xf9, 0x35, 0x59, 0xf0, 0x1d, 0x22, 0x3e, 0x1c, 0xc1, 0x41, 0x9a, 0xaf, 0x26, 0x22, 0x5e,
	0x57, 0x13, 0xf9, 0x5f, 0x75, 0x3b, 0xc0, 0x1f, 0xab, 0xcb, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x0a, 0x2e, 0x08, 0x2a, 0x66, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RawKvClient is the client API for RawKv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RawKvClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// rpc BatchGet(BatchGetRequest) returns (BatchGetResponse) {}
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type rawKvClient struct {
	cc *grpc.ClientConn
}

func NewRawKvClient(cc *grpc.ClientConn) RawKvClient {
	return &rawKvClient{cc}
}

func (c *rawKvClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/kv.RawKv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rawKvClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/kv.RawKv/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RawKvServer is the server API for RawKv service.
type RawKvServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// rpc BatchGet(BatchGetRequest) returns (BatchGetResponse) {}
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

// UnimplementedRawKvServer can be embedded to have forward compatible implementations.
type UnimplementedRawKvServer struct {
}

func (*UnimplementedRawKvServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRawKvServer) Put(ctx context.Context, req *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}

func RegisterRawKvServer(s *grpc.Server, srv RawKvServer) {
	s.RegisterService(&_RawKv_serviceDesc, srv)
}

func _RawKv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.RawKv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKvServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RawKv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RawKvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.RawKv/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RawKvServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RawKv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.RawKv",
	HandlerType: (*RawKvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RawKv_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _RawKv_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvpb.proto",
}

// TxnKvClient is the client API for TxnKv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TxnKvClient interface {
	Transaction(ctx context.Context, opts ...grpc.CallOption) (TxnKv_TransactionClient, error)
	RunOnce(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error)
}

type txnKvClient struct {
	cc *grpc.ClientConn
}

func NewTxnKvClient(cc *grpc.ClientConn) TxnKvClient {
	return &txnKvClient{cc}
}

func (c *txnKvClient) Transaction(ctx context.Context, opts ...grpc.CallOption) (TxnKv_TransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TxnKv_serviceDesc.Streams[0], "/kv.TxnKv/Transaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &txnKvTransactionClient{stream}
	return x, nil
}

type TxnKv_TransactionClient interface {
	Send(*TxnRequest) error
	Recv() (*TxnResponse, error)
	grpc.ClientStream
}

type txnKvTransactionClient struct {
	grpc.ClientStream
}

func (x *txnKvTransactionClient) Send(m *TxnRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *txnKvTransactionClient) Recv() (*TxnResponse, error) {
	m := new(TxnResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *txnKvClient) RunOnce(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error) {
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, "/kv.TxnKv/RunOnce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxnKvServer is the server API for TxnKv service.
type TxnKvServer interface {
	Transaction(TxnKv_TransactionServer) error
	RunOnce(context.Context, *TxnRequest) (*TxnResponse, error)
}

// UnimplementedTxnKvServer can be embedded to have forward compatible implementations.
type UnimplementedTxnKvServer struct {
}

func (*UnimplementedTxnKvServer) Transaction(srv TxnKv_TransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method Transaction not implemented")
}
func (*UnimplementedTxnKvServer) RunOnce(ctx context.Context, req *TxnRequest) (*TxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunOnce not implemented")
}

func RegisterTxnKvServer(s *grpc.Server, srv TxnKvServer) {
	s.RegisterService(&_TxnKv_serviceDesc, srv)
}

func _TxnKv_Transaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TxnKvServer).Transaction(&txnKvTransactionServer{stream})
}

type TxnKv_TransactionServer interface {
	Send(*TxnResponse) error
	Recv() (*TxnRequest, error)
	grpc.ServerStream
}

type txnKvTransactionServer struct {
	grpc.ServerStream
}

func (x *txnKvTransactionServer) Send(m *TxnResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *txnKvTransactionServer) Recv() (*TxnRequest, error) {
	m := new(TxnRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TxnKv_RunOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnKvServer).RunOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.TxnKv/RunOnce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnKvServer).RunOnce(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TxnKv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.TxnKv",
	HandlerType: (*TxnKvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunOnce",
			Handler:    _TxnKv_RunOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transaction",
			Handler:       _TxnKv_Transaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kvpb.proto",
}
